### ISSUE TITLE
Inconsistent behavior

### ISSUE THREAD

**Issue by tomcritchlow** [WICG/scroll-to-text-fragment#114]
Hey there - I'm seeing very inconsistent and sometimes sporadic behavior with scrolltotextfragment. Can you shed some light on this?

I'm seeing:

- Sometimes the text is not highlighted and nothing happens
- Sometimes the text is highlighted but no scroll happens
- Sometimes you need to refresh the page to see anything happen

And - most puzzling is that some URLs work sometimes and not other times. This makes testing and debugging incredibly difficult...

A few examples:

[This one works for me](https://tomcritchlow.com/2020/06/09/quotebacks/#:~:text=a%20small%20tool)

While

[This one does nothing](https://tomcritchlow.com/2020/06/09/quotebacks/#:~:text=a%20small%20tool%20called)

Am I constructing these incorrectly? Why am I seeing inconsistent behavior?

**Comment by atjn** [comment]
Hmmm. Both of those links work perfectly fine for me on Chrome 83 / Windows 10. In my experience, the feature has worked consistently for everything i used it for.

What is your specific setup? It sounds to me like this is a setup-specific issue that should be fixed in [a chromium bug](https://bugs.chromium.org/p/chromium/issues/list), not in the spec.

**Comment by bokand** [comment]
They both work for me too and +1 about filing on crbug.com/ for implementation issues.

that said, there's a few security based [reasons](https://wicg.github.io/scroll-to-text-fragment/#restricting-the-text-fragment) we might avoid invoking the fragment, maybe you were hitting those between runs? the main one I can think of is if you have a popup and try the link cross-origin.

Another case is if you're clicking links from apps/pages that use a redirector (e.g. Twitter's t.co redirector). Those will fail because the [redirect doesn't propagate a user activation](https://crbug.com/1055455).

In any case, if you're still having issues feel free to file a bug with details in crbug.com/new and we can followup there.
