### ISSUE TITLE
Search API, User > Author opt-in and out-out

### ISSUE THREAD

**Issue by felquis** [WICG/scroll-to-text-fragment#115]
I thought this feature was OK until I noticed Google is using it on all search results, making most pages scroll down without the authors allowing it before hand.

### 1
I feel like this API should integrate better with the find-in-page functionality that has no APIs today, and the find-in-page has a similar purpose to allow the user to discover content with-in the page

Image a Search API that helps authors help users to discover content on its own page, scroll to it, see the positions in the page where there's ocurrences, that could affect the URL or not according to the author/user preferrences.

### 2
Let the web authors opt-in this browser functionality instead of opting-out.
Let users opt-in or out this functionality

In general:
![image](https://user-images.githubusercontent.com/736728/84313261-a69e4880-ab3c-11ea-9668-a7af6cb4fffe.png)
https://www.theverge.com/2020/6/4/21280115/google-search-engine-yellow-highlight-featured-snippet-anchor-text#528002986

**Comment by bokand** [comment]
>1

If I understand you correctly, I think this is a UI issue rather than something related to this specification. That is, browsers are free to reuse/integrate the FindInPage UI to highlight and bring the snippet into view.

Specifically in Chrome's case, I agree it's possible we could do more integration with Find-In-Page. As this gets more used and based on feedback this could be improved

If you're talking about an API for authors to use to search their own text, something like this exists but isn't specified well: https://developer.mozilla.org/en-US/docs/Web/API/Window/find

> 2

I think requiring that pages opt-in defeats the purpose. It would lead to confusion if text fragments worked on some pages and not others, effectively precluding a user feature like allow "copy link to selected text".

There is a proposed [opt-out](https://github.com/WICG/scroll-to-text-fragment#current-status) for pages that want to disable it that we're currently trying out in an origin trial.

That said, normative text gives a lot of discretion to the user agent about how the text snippet should be indicated.

Re: user opt-out - I think that's reasonable but up to the UA. UAs are free to allow users to disable scrolling/highlighting a text fragment but different browsers have different philosophies on how much they allow users to customize browser behavior.

**Comment by felquis** [comment]
I know there's great challenge to develop an API to a web browser, so its all just feedbacks.

> If you're talking about an API for authors to use to search their own text, something like this exists but isn't specified well: https://developer.mozilla.org/en-US/docs/Web/API/Window/find

Interesting example, thank you.

--

### 1

This is an universal thing, different between UA but they are all consistent.
![search-api](https://user-images.githubusercontent.com/736728/84537659-9619d980-acc6-11ea-9aea-ed61190234d0.gif)

- Open Search width a text _method_
- Next, Previous _event/method_
- Ocurrences + Position (see the ocurrence lines on the scrollbar) _getter_
- Close search - _event/method_

It already scrolls the page, highlights the text, to me it is a matter of matching this interface and somehow take an URL out of it. It doesnt seems too far away from reality to me. But I understand it might be way more challenging to actually make it work with all the web variety out there.

--

### 2
I also suggest a context menu "Copy link to text" somehow https://github.com/WICG/scroll-to-text-fragment#:~:text=an%20example%20URL%20encoding%20some%20text%20to%20indicate%20on since it is too easy for an user to copy an anchor link with right click, but the link to a text is useful but complicated to come up with as an user.

![search-api-context-menu](https://user-images.githubusercontent.com/736728/84538490-1e4cae80-acc8-11ea-9f62-950aaf7f66a7.gif)

--

> Re: user opt-out - I think that's reasonable
But ok 👍 We can always opt-out 😄 

Yeah, it wasn't the kind of feature I got excited when I first saw it. Like I do when "Look how you can control your webpage with this new amazing feature"... but scared like "Look how can google control your page without your awareness" I only discovered it because the search results UX changed dramatically with this new update.

I hope this abstract idea of Search API gives you a spark of creativity. Have a wonderful day.

**Comment by bokand** [comment]
> I also suggest a context menu "Copy link to text" somehow 

FYI: This is currently in-development, you can enable the experimental implementation using chrome://flags/#copy-link-to-text

There's also an [official extension](https://chrome.google.com/webstore/detail/link-to-text-fragment/pbcodcjpfjdpcineamnnmbkkmkdpajjg).

> I hope this abstract idea of Search API gives you a spark of creativity

It's an interesting idea but this repo is probably not the right place for it - [WICG discourse](https://discourse.wicg.io/) might be a good place to propose and discuss new ideas.

I'm going to close issue this as there's nothing actionable specific to this proposal. Thanks for the discussion!
