### ISSUE TITLE
Altering URLs leads to confusing link-sharing UX

### ISSUE THREAD

**Issue by onemahon** [WICG/scroll-to-text-fragment#117]
Setting aside the concerns other issue-creators have brought up about this feature regarding the way it modifies and interferes with the original website itself, I wanted to ask about the fact that this feature leads to corrupting the URL of the page.

Many sites have organized their information around easy-to-interpret URLs, and more importantly, **easy-to-share** urls. When opening a link with the scroll-to-text specified in the URL, that text remains in place as if it's a relevant param to the website itself.

It's a very common use case to use keywords to search for something that you wind up wanting to share; but currently, when you go to share it, you'll wind up sharing a corrupted link that scrolls the recipient to an arbitrary anchor point that's only related to whatever you yourself searched for originally.

While this issue is relatively easy to overcome on desktop, if you know enough to copy the correct portion of the URL without the `:~:text=` params; but it's compounded infinitely on Android devices, wherein Chrome makes it (surprisingly) difficult to edit URLs (going so far as to hide the URL from the 'edit' box when you put your cursor in there).

Moreover, I imagine the vast majority of people who interact with this feature will never have a clue that the yellow highlight areas they're seeing have anything to do with what's in the URL.

Can this spec be adjusted to force the client to remove the params from the URL as soon as the page loads, or something along those lines? Which would also make it so that refreshing the page would be a "full" refresh, such that the user lands back at the top of the document.

**Comment by bokand** [comment]
This kind of behavior is best left for UAs to decide, since it doesn't affect interop between browsers and allows them to compete on providing the best experience. That said, the specification now provides some [good default guidelines](https://wicg.github.io/scroll-to-text-fragment/#urls-in-ua-features) for this.

I believe Chrome will match this behavior in an upcoming release (when the highlight is dismissed, the text-fragment is removed from the URL bar)
