### ISSUE TITLE
How to disable?

### ISSUE THREAD

**Issue by PeopleInside** [WICG/scroll-to-text-fragment#122]
Hi, I know this project is important and look wonderful for someone and for someone else that is integrating with browsers... for example Google Chrome that is starting to support this with the collaboration of some websites that add the code to be compatible... but how about users that don't like this?

The question is: how to disable this?

I'm reading about users unhappy by this forcing and I agree with that users.
This function should be optional and not forced to all but also seems I'm not finding a way to stop this function on Chrome.

Often it happens I need search on the web than i take the URL to share with other people and I give the wrong URL... wrong because you are editing URL'S so ... I need to remember to select just the right part without the text highlight.

I really don't need this function and really don't want.
How can be disabled?

I don't like a project when this looks to be an imposition and cannot be a decision of the users to use or not.

**Comment by nickburris** [comment]
On Google Chrome you can disable the feature by flag at chrome://flags/#enable-text-fragment-anchor

Note that this does not stop websites from adding a text directive to the URL, so you may still encounter a scroll to text link in the wild, though websites may [check if your browser supports the feature](https://wicg.github.io/scroll-to-text-fragment/#feature-detectability) before providing such a link.

**Comment by PeopleInside** [comment]
I need to solve the URL issue so this is not helping to solve the issue... also flags are not stable settings to edit.

**Comment by PeopleInside** [comment]
At the moment the solution seems to not use Chrome.
If this will be added in other browser I will open issues on other browser reporting this bad forcing and issue caused. User should be able to decide not to be forced to see edited URLS and Pages. I really don't like this way to impose this function.

**Comment by bokand** [comment]
From the perspective of this as a web standard, I think this is out of scope since that's a decision individual browsers can make. The issue here is specifically to Chrome and how we implement this functionality; I've filed https://crbug.com/1097812 to track this in Chrome.

User configurable options are a tricky balance - customization is nice but making everything customization makes the browser complicated and more difficult to use. One of Chromium's core principles is [simplicity](https://www.chromium.org/developers/core-principles#sites-canvas-main-content:~:text=Simplicity,-Google%20is%20all%20about) and minimizing configuration options so this isn't something we'd make configurable; we'd prefer to make the feature work well for the vast majority of users. (This is specifically for Chrome, it's a totally valid approach for other browsers to put more emphasis on user configuration and having a switch to control this could make sense in that scenario. Nothing specified in this repo precludes that).

That said, we've received lots of useful feedback about things users are finding difficult/annoying about these links and we're working on changes to make this better. Making the highlight disappear shortly after load should help. I agree with you the URL sharing issue is a problem (thanks for the feedback!) and something we haven't yet considered. Will track in the crbug above.

**Comment by PeopleInside** [comment]
@bokand  Not fully a solution but is a start.
Yes the URL sharing is very stressful, 
It happens I pasted the wrong URL because of this new forced function.

The solution for now seems to leave Chrome and use another browser.
Users are asking how to disable that!
Some related topics:
How to disable highlights in snippets: https://support.google.com/websearch/thread/52338234?hl=en&msgid=52338234
Disable highlights and auto-scroll from searches: https://support.google.com/chrome/thread/53700706
Turn off auto-highlight??: https://support.google.com/chrome/thread/18146567?hl=en

Thanks anyway,  thanks for opening the Chrome issue about URL.

**Comment by PeopleInside** [comment]
Anyone look here there is an extension that solve the Chrome behaviour: https://chrome.google.com/webstore/detail/disable-google-search-tex/ompocnnmgiaoieoanemepjflbokldhom

**Comment by teohhanhui** [comment]
Instead of an extension, you can also just use a userscript (with e.g. Violentmonkey) for this: https://greasyfork.org/en/scripts/431107-remove-text-fragment
