### ISSUE TITLE
Collapsed page sections

### ISSUE THREAD

**Issue by sloanlance** [WICG/scroll-to-text-fragment#132]
How would this handle collapsed page sections that aren't visible when the page loads?  The Wikipedia cat URL example given points to a section that's collapsed when the page loads in a mobile browser. Even using the browser's find-in-page feature can't (or won't) find text located in those sections.

**Comment by bokand** [comment]
Yeah, this kind of pattern is a problem for a number of features including this one. It'd require page authors to do some work.

I think the recently shipped (in Chrome) [content-visibility](https://github.com/WICG/display-locking) style is the best answer. It's explicitly designed so that content that's not rendered will automatically become visible/expanded when Find-in-Page or Text-Fragments are invoked on it and allows pages to react to it with the `beforematch` event.

**Comment by bokand** [comment]
FYI: This should now work seamlessly with `hidden=until-found` and `<details>` - would work on Wikipedia modulo [some nuance](https://twitter.com/david_bokan/status/1567381136795439104) in how Wikipedia uses hidden=until-found.
