### ISSUE TITLE
Offer also plain scroll-to-id mode, in addition to scroll-to-text-fragment mode

### ISSUE THREAD

**Issue by jidanni** [WICG/scroll-to-text-fragment#144]
Let's go back to https://web.dev/text-fragments/ .
You see at the top of the article where he has those red boxes?

Well I'm saying that [the extension](https://chrome.google.com/webstore/detail/link-to-text-fragment/pbcodcjpfjdpcineamnnmbkkmkdpajjg) is great. But what if we want it to also do just a little less?
I.e., how about some "mode" within the extension that just shows those red boxes
and offers links to them?

Case in point: we want to come up with the link
" https://wiki.debian.org/resolv.conf#Configuring_dhclient "
but of course we needed F12 Developer Tools to find that id=
and then cobble it together with # by hand.

(Yes, there is a workaround: using the extension one can come up with
https://wiki.debian.org/resolv.conf#Configuring_dhclient:~:text=Configuring%20dhclient
and then trim it by hand to get
https://wiki.debian.org/resolv.conf#Configuring_dhclient
and then test it in a browser (even w3m works!)
to confirm that it will go where one expects.)

**Comment by bokand** [comment]
Thanks for filing. It sounds like this is a request for the link-to-text-fragment extension rather than this API; you'd be better off filing an issue on the extension's [GitHub repo](https://github.com/GoogleChromeLabs/link-to-text-fragment)

That said, the extension is minimalist in its approach so I suspect isn't something they'd be enthusiastic to add. But you could always clone the extension and make your own changes/additions to it.

**Comment by purpleslurple** [comment]
Try this:
https://purpleslurple.com/ps.php?theurl=https%3A%2F%2Fweb.dev%2Ftext-fragments%2F#purp248

**Comment by jidanni** [comment]
> Try this: https://purpleslurple.com/ps.php?theurl=https%3A%2F%2Fweb.dev%2Ftext-fragments%2F#purp248

Ah, https://purpleslurple.com/ps.php . Well that works great... until one day when that site goes bankrupt.

I would have it make red boxes around id='s that lie within the target page, and at the top of each box, offer a copy link button.
The result would be example.com/bla#fun i.e., links without depending on any third party website.

**Comment by purpleslurple** [comment]
Yea, it's an 18 year old hack. Site has been around since 2002 (mostly :)
Concerned about longevity? Available on github. Run it on localhost. My
localhost links look like your localhost links. PHP has deprecated
functions, HTML specs change, Chrome/Google changes, sites come and go.
Fork it, fix it, tweak it.

I've been waiting for browser implementation for 18 years. You guys are
getting there. Keep up the good work.

Regards,

Matt
