### ISSUE TITLE
hidden=until-found and auto-expanding <details>

### ISSUE THREAD

**Issue by josepharhar** [WICG/scroll-to-text-fragment#173]
Hello, I've been working on two similar features in chromium: [hidden=until-found](https://github.com/whatwg/html/issues/6040) and [auto-expanding details elements](https://github.com/whatwg/html/pull/6466).

Both of these features revolve around revealing content in response to find-in-page and element fragments, and I'd also like scroll-to-text-fragment to be supported - I'd like for text matches from scroll-to-text-fragment queries within closed details elements and hidden=until-found subtrees to allow the content to be revealed so scroll-to-text-fragment can scroll to it. I noticed that scroll-to-text-fragment appears to be here instead of the html spec... should I make a PR here in order for scroll-to-text-fragment support to be specified for these features?

**Comment by bokand** [comment]
Yes, until we get a second implementer interested in text-fragments we can't PR on the HTML spec so I think here is fine for now.

**Comment by bokand** [comment]
Closing out old issues - I think this one is resolved since the [algorithm includes expanding these sections](https://wicg.github.io/scroll-to-text-fragment/#:~:text=In%20scroll%20to%20the%20fragment%2C%20handle%20a%20indicated%20part%20that%20is%20a%20range%20and%20also%20prevent%20fragment%20scrolling%20if%20the%20force%2Dload%2Dat%2Dtop%20policy%20is%20enabled.%20Make%20the%20following%20changes%3A).
