### ISSUE TITLE
Example 12 (security/privacy) seems unneeded

### ISSUE THREAD

**Issue by annevk** [WICG/scroll-to-text-fragment#180]
>  A malicious page embeds a cross-origin victim in an iframe. The victim page contains information sensitive to the user. The malicious page navigates the victim to a text fragment. Since a successful fragment match will cause focus, the malicious page can determine if the text appears in the victim by listening for a blur event in its own document. 

This attack is ruled out by the processing model. If we wanted to include examples that are already ruled out, we'd have to include many more. (But also, we'd have to update the surrounding text which assumes they are not ruled out.)

**Comment by bokand** [comment]
I wanted to include this case, even though it's precluded by our processing model, to give readers some idea of the kinds of cases we need to be worried about. But you're right that it doesn't fit with the other examples or surrounding prose.

I'll see if I can rework this section to make this clearer.

**Comment by bokand** [comment]
Actually, re-reading this, text fragments in an iframe aren't strictly precluded by the processing model (this changed but not since this was filed) since we only perform the top-level [browsing context check for cross-origin initiators](https://wicg.github.io/scroll-to-text-fragment/#:~:text=If%20the%20navigationParam%E2%80%99s%20request%20has%20a%20sec%2Dfetch%2Dsite%20header%20and%20its%20value%20is%20%22same%2Dorigin%22%20set%20allowTextFragmentDirective%20to%20true%20and%20abort%20these%20sub%2Dsteps.). This enables e.g. an iframe'd document navigating itself to a text fragment.

That said, it's done via sec-fetch-site which is wrong per #179 so I'll need to address it there.
