### ISSUE TITLE
Searching inside spesific element

### ISSUE THREAD

**Issue by valtlai** [WICG/scroll-to-text-fragment#55]
The current spec supports [fallback syntax](https://wicg.github.io/ScrollToTextFragment/#determine-if-fragment-id-is-needed), like `#comments:~:word`. The string `word` is searched on the whole page and if not found, the browser will fallback to the regular id `#comments`.

I think we should consider another approach, if not done yet. We could search inside the element matched by the regular id fragment (here `#comments`) instead of the whole page. The fallback would be unchanged, the whole element.

**Comment by bokand** [comment]
We've thought about this but it seems like it'd add complexity to the functionality and I'm not sure it provides much additional value. It can add specificity but I believe the most recent proposal already addresses issues regarding ambiguity (i.e. context terms) so I don't really see the benefit here, you should already be able to craft a URL to exactly the text you want.

**Comment by Madis0** [comment]
The additional value is (or should be) compatibility with UAs that don't implement this.

For example, if you share a link
`https://github.com/WICG/ScrollToTextFragment/issues/55#:~:text=We%27ve%20thought%20about%20this`
then any current UAs just consider the anchor text as a noise and simply open the page itself.

However, if you share a link to a proper anchor
`https://github.com/WICG/ScrollToTextFragment/issues/55#issuecomment-542605524-permalink`
then the user (and UA) has the most context it can get even without highlighting specific text.

Combining the two in a way that would work with legacy UAs would be the most beneficial to users.

**Comment by bokand** [comment]
I'm not sure I understand your point. The issue here is how to handle the case where both an element anchor and a text snippet are provided. How would changing the semantics of what we do in this case help non-implementing UAs? If you specify the text snippet to a non-implementing UA the fragment is interpreted as noise regardless of how the behavior is spec'ed.

> Combining the two in a way that would work with legacy UAs would be the most beneficial to users.

I don't believe such a way exists. If you have an example I'd be happy to be proven wrong :)

**Comment by Madis0** [comment]
Well, it is mostly about finding a character that the UAs usually ignore as a part of the URL anchor, so that compatible UAs can tailor the proceeding characters as a text to find. Or maybe this text should be elsewhere in the URL, such as spoofing the username-password part?

`https://We%27ve%20thought%20about%20this::@github.com/WICG/ScrollToTextFragment/issues/55#issuecomment-542605524-permalink`

Note the `::@` as an invalid HTTP auth syntax.

**Comment by bokand** [comment]
(Sorry for the silence) Thanks for the interesting idea. We went down a similar road trying to use `##` as the delimiter, which is invalid in a fragment (and therefore should be unused). We found 2 things:

 - Just because something is invalid, doesn't mean it doesn't already exist. We found lots of cases of URLs containing `##` already.
 - Introducing previously invalid characters means we invalidate every existing implementation. The major browsers might fallback gracefully, but there's an unknowable number of tools and infrastructure that might choke on these invalid URLs.

Regarding searching inside a specific element, I've been thinking about that more recently. Issue #75 discusses the same thing so I'm going to close this in favor of that one. Feel free to continue the discussion there.
